version: '3.8'

services:
  youtube-transcript-mcp:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SERVER_URL=${SERVER_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - AUTHORIZED_EMAILS=${AUTHORIZED_EMAILS}
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - ENABLE_WARP=${ENABLE_WARP:-true}
    env_file:
      - .env
    volumes:
      - oauth_data:/app
      - warp_data:/var/lib/cloudflare-warp
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

volumes:
  oauth_data:
  warp_data:
